
# [START kubernetes_deployment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoapp
  labels:
    app: djangoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangoapp
  template:
    metadata:
      labels:
        app: djangoapp
    spec:
      containers:
      - name: djangoapp
        image: us-central1-docker.pkg.dev/icardio-ai-393417/reticulum-test/djangoapp:test
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - containerPort: 8000  
# [END kubernetes_deployment]

---

apiVersion: v1
kind: Service
metadata:
  name: djangoapp
  labels:
    app: djangoapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: djangoapp
# [END service]
